### ISSUE TITLE
have a 404 while accessing http://0.0.0.0:8080/

### ISSUE THREAD

**Issue by lduboeuf** [creationix/hexes#2]
hello,
```
luvi v2.7.4
rex: 8.37 2015-04-28
libuv: 1.9.1
ssl: OpenSSL 1.0.2g  1 Mar 2016, lua-openssl 0.5.1
```
 can't make hexes diplayed with `luvi .`
 http://0.0.0.0:8080 or http://0.0.0.0:8080/index.html return 404
fs.stat(path) always return nil: https://github.com/creationix/weblit/blob/master/libs/weblit-static.lua#L32

thought it was a `luvit-loader` thing but didn't work either.

**Comment by lduboeuf** [comment]
`luvit main.lua` works fine.

**Comment by lduboeuf** [comment]
if i add `.use(require('weblit-static')(pathJoin(uv.cwd(), "web"))` it works fine with either `luvi .` or luvit main.lua if i am in the directory. but not if i'm outside of it.

**Comment by creationix** [comment]
Right, if you start it outside the directory, you'll need to use something other than cwd.

In luvit 2.x the require system injects a `module` global that contains `module.dir` you can use for relative paths that is immune to changing `uv.cwd()` values.

In luvit-loader we can't depend on injected values since it's using lua's native require unmodified.  Internally it uses debug to get the path of the calling file: https://github.com/luvit/lit/blob/master/luvit-loader.lua#L228-L231

Also luvit has a package that makes this code more generically available (which ironically doesn't work well with luvit's require system).  https://github.com/luvit/luvit/blob/master/deps/resource.lua

You could add this resource package to your application as a normal lit dependency and use it to get the relative path from your weblit main config.

``` lua
require('resource').resolve('./web') -> web relative to this file
```

**Comment by lduboeuf** [comment]
allright, thanks for your feedback.
not so easy to get started with all samples code that use not the same way ( mode.dir, uv.cwd, bundle, etc... ).
Maybe it would be nice to have a `lit make lit://creationix/hexes` working then ;-)

**Comment by lduboeuf** [comment]
please make  `lit make lit://creationix/hexes` work again, still have a 404 ;-)

**Comment by creationix** [comment]
ok, since you said please :)

Working on it...

**Comment by creationix** [comment]
Ok, published new version.

I added support to weblit-static to support bundle paths.

https://github.com/creationix/weblit/commit/132a5ca373e3ce8462976e56e745fe3030af7d8b

**Comment by lduboeuf** [comment]
:+1:  ;-)
